org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
org.gradle.parallel=true
org.gradle.caching=true

minecraft_version=1.21.1
neo_version=21.1.209

mod_id=airsystem
mod_name=Project AirSystem
mod_license=GPL-3.0-or-later
mod_version=1.0.0
mod_group_id=com.rbxlu.airsystem
mod_authors=RBXLU
mod_description=UAVs, air raid alarms and anti-aircraft systems for Minecraft.
