package com.rbxlu.airsystem.client.model;

import net.minecraft.client.model.geom.PartPose;
import net.minecraft.client.model.geom.builders.CubeListBuilder;
import net.minecraft.client.model.geom.builders.LayerDefinition;
import net.minecraft.client.model.geom.builders.MeshDefinition;
import net.minecraft.client.model.geom.builders.PartDefinition;

// Generated by tools/build_radar.py — edit the script, not this file.
public final class RadarLayers {
    public static LayerDefinition createRadar() {
        MeshDefinition mesh = new MeshDefinition();
        PartDefinition root = mesh.getRoot();

        PartDefinition base = root.addOrReplaceChild("base",
                CubeListBuilder.create()
                        .texOffs(0, 0).addBox(-14.0F, -3.0F, -14.0F, 28.0F, 3.0F, 28.0F)
                        .texOffs(59, 104).addBox(11.0F, -5.0F, -13.0F, 2.0F, 2.0F, 2.0F)
                        .texOffs(68, 104).addBox(-13.0F, -5.0F, -13.0F, 2.0F, 2.0F, 2.0F)
                        .texOffs(77, 104).addBox(11.0F, -5.0F, 11.0F, 2.0F, 2.0F, 2.0F)
                        .texOffs(86, 104).addBox(-13.0F, -5.0F, 11.0F, 2.0F, 2.0F, 2.0F)
                        .texOffs(0, 32).addBox(-10.0F, -12.0F, -10.0F, 20.0F, 9.0F, 20.0F)
                        .texOffs(0, 62).addBox(-8.0F, -14.0F, -8.0F, 16.0F, 2.0F, 16.0F)
                        .texOffs(0, 96).addBox(-6.0F, -10.0F, 9.0F, 12.0F, 5.0F, 2.0F)
                        .texOffs(82, 81).addBox(-7.0F, -9.0F, -11.0F, 1.0F, 4.0F, 4.0F)
                        .texOffs(65, 62).addBox(-3.0F, -24.0F, -3.0F, 6.0F, 10.0F, 6.0F),
                PartPose.offset(0.0F, 0.0F, 0.0F));

        PartDefinition dish = root.addOrReplaceChild("dish",
                CubeListBuilder.create()
                        .texOffs(49, 81).addBox(-4.0F, -4.0F, -4.0F, 8.0F, 4.0F, 8.0F)
                        .texOffs(110, 81).addBox(-1.0F, -26.0F, -1.0F, 2.0F, 6.0F, 2.0F),
                PartPose.offset(0.0F, -24.0F, 0.0F));

        dish.addOrReplaceChild("dish_r0",
                CubeListBuilder.create()
                        .texOffs(81, 32).addBox(11.0F, -16.0F, 0.0F, 2.0F, 16.0F, 3.0F),
                PartPose.offsetAndRotation(-0.0F, -4.0F, 2.0F, 0.3142F, -0.0000F, 0.0000F));

        dish.addOrReplaceChild("dish_r1",
                CubeListBuilder.create()
                        .texOffs(92, 32).addBox(-13.0F, -16.0F, 0.0F, 2.0F, 16.0F, 3.0F),
                PartPose.offsetAndRotation(-0.0F, -4.0F, 2.0F, 0.3142F, -0.0000F, 0.0000F));

        dish.addOrReplaceChild("dish_r2",
                CubeListBuilder.create()
                        .texOffs(29, 96).addBox(-13.0F, -2.0F, 0.0F, 26.0F, 2.0F, 3.0F),
                PartPose.offsetAndRotation(-0.0F, -4.0F, 2.0F, 0.3142F, -0.0000F, 0.0000F));

        dish.addOrReplaceChild("dish_r3",
                CubeListBuilder.create()
                        .texOffs(0, 104).addBox(-13.0F, -16.0F, 0.0F, 26.0F, 2.0F, 3.0F),
                PartPose.offsetAndRotation(-0.0F, -4.0F, 2.0F, 0.3142F, -0.0000F, 0.0000F));

        dish.addOrReplaceChild("dish_r4",
                CubeListBuilder.create()
                        .texOffs(0, 81).addBox(-11.0F, -14.0F, 1.0F, 22.0F, 12.0F, 2.0F),
                PartPose.offsetAndRotation(-0.0F, -4.0F, 2.0F, 0.3142F, -0.0000F, 0.0000F));

        dish.addOrReplaceChild("dish_r5",
                CubeListBuilder.create()
                        .texOffs(93, 81).addBox(-1.0F, -9.0F, -5.0F, 2.0F, 2.0F, 6.0F),
                PartPose.offsetAndRotation(-0.0F, -4.0F, 2.0F, 0.3142F, -0.0000F, 0.0000F));

        return LayerDefinition.create(mesh, 128, 128);
    }
    private RadarLayers() {
    }
}
