package com.rbxlu.airsystem.client.model;

import com.rbxlu.airsystem.content.turret.TurretKind;

import net.minecraft.client.model.geom.PartPose;
import net.minecraft.client.model.geom.builders.CubeListBuilder;
import net.minecraft.client.model.geom.builders.LayerDefinition;
import net.minecraft.client.model.geom.builders.MeshDefinition;
import net.minecraft.client.model.geom.builders.PartDefinition;

// Generated by tools/build_turrets.py — edit the script, not this file.
public final class TurretLayers {
    public static LayerDefinition createGepard() {
        MeshDefinition mesh = new MeshDefinition();
        PartDefinition root = mesh.getRoot();

        PartDefinition hull = root.addOrReplaceChild("hull",
                CubeListBuilder.create()
                        .texOffs(0, 105).addBox(18.0F, -15.0F, -48.0F, 6.0F, 3.0F, 96.0F)
                        .texOffs(0, 0).addBox(19.0F, -12.0F, -47.0F, 4.0F, 10.0F, 94.0F)
                        .texOffs(0, 428).addBox(17.0F, -11.0F, -40.0F, 8.0F, 11.0F, 10.0F)
                        .texOffs(167, 397).addBox(17.0F, -11.0F, -29.0F, 8.0F, 11.0F, 11.0F)
                        .texOffs(37, 428).addBox(17.0F, -11.0F, -17.0F, 8.0F, 11.0F, 10.0F)
                        .texOffs(206, 397).addBox(17.0F, -11.0F, -6.0F, 8.0F, 11.0F, 11.0F)
                        .texOffs(74, 428).addBox(17.0F, -11.0F, 6.0F, 8.0F, 11.0F, 10.0F)
                        .texOffs(245, 397).addBox(17.0F, -11.0F, 17.0F, 8.0F, 11.0F, 11.0F)
                        .texOffs(111, 428).addBox(17.0F, -11.0F, 29.0F, 8.0F, 11.0F, 10.0F)
                        .texOffs(408, 428).addBox(17.0F, -13.0F, -47.0F, 8.0F, 12.0F, 7.0F)
                        .texOffs(439, 428).addBox(17.0F, -13.0F, 40.0F, 8.0F, 12.0F, 7.0F)
                        .texOffs(205, 105).addBox(-24.0F, -15.0F, -48.0F, 6.0F, 3.0F, 96.0F)
                        .texOffs(197, 0).addBox(-23.0F, -12.0F, -47.0F, 4.0F, 10.0F, 94.0F)
                        .texOffs(148, 428).addBox(-25.0F, -11.0F, -40.0F, 8.0F, 11.0F, 10.0F)
                        .texOffs(284, 397).addBox(-25.0F, -11.0F, -29.0F, 8.0F, 11.0F, 11.0F)
                        .texOffs(185, 428).addBox(-25.0F, -11.0F, -17.0F, 8.0F, 11.0F, 10.0F)
                        .texOffs(323, 397).addBox(-25.0F, -11.0F, -6.0F, 8.0F, 11.0F, 11.0F)
                        .texOffs(222, 428).addBox(-25.0F, -11.0F, 6.0F, 8.0F, 11.0F, 10.0F)
                        .texOffs(362, 397).addBox(-25.0F, -11.0F, 17.0F, 8.0F, 11.0F, 11.0F)
                        .texOffs(259, 428).addBox(-25.0F, -11.0F, 29.0F, 8.0F, 11.0F, 10.0F)
                        .texOffs(470, 428).addBox(-25.0F, -13.0F, -47.0F, 8.0F, 12.0F, 7.0F)
                        .texOffs(0, 450).addBox(-25.0F, -13.0F, 40.0F, 8.0F, 12.0F, 7.0F)
                        .texOffs(0, 205).addBox(-17.0F, -21.0F, -43.0F, 34.0F, 12.0F, 86.0F)
                        .texOffs(241, 205).addBox(-17.0F, -26.0F, -30.0F, 34.0F, 5.0F, 66.0F)
                        .texOffs(401, 397).addBox(-17.0F, -14.0F, -45.0F, 34.0F, 5.0F, 17.0F)
                        .texOffs(31, 450).addBox(-17.0F, -20.0F, -40.0F, 34.0F, 6.0F, 12.0F)
                        .texOffs(260, 470).addBox(-17.0F, -25.0F, -35.0F, 34.0F, 5.0F, 7.0F)
                        .texOffs(0, 470).addBox(-17.0F, -13.0F, 40.0F, 34.0F, 4.0F, 11.0F)
                        .texOffs(343, 470).addBox(-17.0F, -17.0F, 43.0F, 34.0F, 4.0F, 8.0F)
                        .texOffs(132, 486).addBox(-17.0F, -21.0F, 46.0F, 34.0F, 4.0F, 5.0F)
                        .texOffs(170, 470).addBox(-9.0F, -28.0F, -28.0F, 18.0F, 2.0F, 11.0F)
                        .texOffs(124, 450).addBox(-8.0F, -28.0F, 24.0F, 16.0F, 2.0F, 16.0F)
                        .texOffs(282, 450).addBox(-17.0F, -27.0F, 30.0F, 4.0F, 5.0F, 12.0F)
                        .texOffs(425, 354).addBox(18.0F, -21.0F, -22.0F, 6.0F, 6.0F, 24.0F)
                        .texOffs(61, 397).addBox(18.0F, -21.0F, 14.0F, 6.0F, 6.0F, 20.0F)
                        .texOffs(0, 397).addBox(-24.0F, -21.0F, -22.0F, 6.0F, 6.0F, 24.0F)
                        .texOffs(114, 397).addBox(-24.0F, -21.0F, 14.0F, 6.0F, 6.0F, 20.0F),
                PartPose.offset(0.0F, 0.0F, 0.0F));

        PartDefinition turret = hull.addOrReplaceChild("turret",
                CubeListBuilder.create()
                        .texOffs(157, 304).addBox(-15.0F, -6.0F, -20.0F, 30.0F, 6.0F, 40.0F)
                        .texOffs(0, 304).addBox(-17.0F, -11.0F, -22.0F, 34.0F, 5.0F, 44.0F)
                        .texOffs(298, 304).addBox(-15.0F, -17.0F, -20.0F, 30.0F, 6.0F, 40.0F)
                        .texOffs(91, 470).addBox(-15.0F, -5.0F, -24.0F, 30.0F, 5.0F, 9.0F)
                        .texOffs(428, 470).addBox(-15.0F, -10.0F, -22.0F, 30.0F, 5.0F, 7.0F)
                        .texOffs(211, 486).addBox(-15.0F, -15.0F, -19.0F, 30.0F, 5.0F, 4.0F)
                        .texOffs(0, 354).addBox(-13.0F, -19.0F, -20.0F, 26.0F, 2.0F, 40.0F)
                        .texOffs(0, 486).addBox(1.0F, -21.0F, -4.0F, 10.0F, 2.0F, 10.0F)
                        .texOffs(41, 486).addBox(-12.0F, -24.0F, -14.0F, 8.0F, 5.0F, 6.0F)
                        .texOffs(457, 486).addBox(-11.0F, -23.0F, -15.0F, 6.0F, 2.0F, 1.0F)
                        .texOffs(105, 486).addBox(-4.0F, -23.0F, -19.0F, 8.0F, 5.0F, 5.0F),
                PartPose.offset(0.0F, -26.0F, 0.0F));

        turret.addOrReplaceChild("turret_r0",
                CubeListBuilder.create()
                        .texOffs(315, 450).addBox(-10.0F, -14.0F, 0.0F, 20.0F, 14.0F, 2.0F),
                PartPose.offsetAndRotation(-0.0F, -23.0F, -18.0F, 0.3840F, -0.0000F, 0.0000F));

        turret.addOrReplaceChild("turret_r1",
                CubeListBuilder.create()
                        .texOffs(70, 486).addBox(-8.0F, -12.0F, -1.0F, 16.0F, 10.0F, 1.0F),
                PartPose.offsetAndRotation(-0.0F, -23.0F, -18.0F, 0.3840F, -0.0000F, 0.0000F));

        PartDefinition barrels = turret.addOrReplaceChild("barrels",
                CubeListBuilder.create()
                        .texOffs(287, 354).addBox(17.0F, -7.0F, 4.0F, 8.0F, 11.0F, 26.0F)
                        .texOffs(296, 428).addBox(18.0F, -9.0F, 14.0F, 6.0F, 5.0F, 16.0F)
                        .texOffs(360, 450).addBox(18.0F, -5.0F, -5.7F, 6.0F, 6.0F, 10.0F)
                        .texOffs(133, 354).addBox(19.0F, -4.0F, -40.0F, 4.0F, 4.0F, 34.0F)
                        .texOffs(280, 486).addBox(18.5F, -4.5F, -43.0F, 5.0F, 5.0F, 3.0F)
                        .texOffs(356, 354).addBox(-25.0F, -7.0F, 4.0F, 8.0F, 11.0F, 26.0F)
                        .texOffs(341, 428).addBox(-24.0F, -9.0F, 14.0F, 6.0F, 5.0F, 16.0F)
                        .texOffs(393, 450).addBox(-24.0F, -5.0F, -5.7F, 6.0F, 6.0F, 10.0F)
                        .texOffs(210, 354).addBox(-23.0F, -4.0F, -40.0F, 4.0F, 4.0F, 34.0F)
                        .texOffs(297, 486).addBox(-23.5F, -4.5F, -43.0F, 5.0F, 5.0F, 3.0F)
                        .texOffs(189, 450).addBox(-17.0F, -5.0F, 8.0F, 34.0F, 6.0F, 12.0F),
                PartPose.offset(0.0F, -8.0F, -18.0F));

        PartDefinition radar = turret.addOrReplaceChild("radar",
                CubeListBuilder.create()
                        .texOffs(229, 470).addBox(-4.0F, -5.0F, -3.0F, 8.0F, 6.0F, 7.0F),
                PartPose.offset(0.0F, -19.0F, 16.0F));

        radar.addOrReplaceChild("radar_r0",
                CubeListBuilder.create()
                        .texOffs(386, 428).addBox(12.0F, -18.0F, 0.0F, 2.0F, 18.0F, 3.0F),
                PartPose.offsetAndRotation(-0.0F, -5.0F, 0.0F, 0.2793F, -0.0000F, 0.0000F));

        radar.addOrReplaceChild("radar_r1",
                CubeListBuilder.create()
                        .texOffs(397, 428).addBox(-14.0F, -18.0F, 0.0F, 2.0F, 18.0F, 3.0F),
                PartPose.offsetAndRotation(-0.0F, -5.0F, 0.0F, 0.2793F, -0.0000F, 0.0000F));

        radar.addOrReplaceChild("radar_r2",
                CubeListBuilder.create()
                        .texOffs(331, 486).addBox(-14.0F, -2.0F, 0.0F, 28.0F, 2.0F, 3.0F),
                PartPose.offsetAndRotation(-0.0F, -5.0F, 0.0F, 0.2793F, -0.0000F, 0.0000F));

        radar.addOrReplaceChild("radar_r3",
                CubeListBuilder.create()
                        .texOffs(394, 486).addBox(-14.0F, -18.0F, 0.0F, 28.0F, 2.0F, 3.0F),
                PartPose.offsetAndRotation(-0.0F, -5.0F, 0.0F, 0.2793F, -0.0000F, 0.0000F));

        radar.addOrReplaceChild("radar_r4",
                CubeListBuilder.create()
                        .texOffs(426, 450).addBox(-12.0F, -16.0F, 1.0F, 24.0F, 14.0F, 2.0F),
                PartPose.offsetAndRotation(-0.0F, -5.0F, 0.0F, 0.2793F, -0.0000F, 0.0000F));

        radar.addOrReplaceChild("radar_r5",
                CubeListBuilder.create()
                        .texOffs(314, 486).addBox(-1.0F, -10.0F, -5.0F, 2.0F, 2.0F, 6.0F),
                PartPose.offsetAndRotation(-0.0F, -5.0F, 0.0F, 0.2793F, -0.0000F, 0.0000F));

        return LayerDefinition.create(mesh, 512, 512);
    }

    public static LayerDefinition createSlinger() {
        MeshDefinition mesh = new MeshDefinition();
        PartDefinition root = mesh.getRoot();

        PartDefinition hull = root.addOrReplaceChild("hull",
                CubeListBuilder.create()
                        .texOffs(0, 0).addBox(-17.0F, -10.0F, -22.0F, 34.0F, 8.0F, 44.0F)
                        .texOffs(37, 138).addBox(6.0F, -4.0F, -14.0F, 5.0F, 4.0F, 5.0F)
                        .texOffs(58, 138).addBox(6.0F, -4.0F, 9.0F, 5.0F, 4.0F, 5.0F)
                        .texOffs(79, 138).addBox(-11.0F, -4.0F, -14.0F, 5.0F, 4.0F, 5.0F)
                        .texOffs(100, 138).addBox(-11.0F, -4.0F, 9.0F, 5.0F, 4.0F, 5.0F)
                        .texOffs(0, 53).addBox(-13.0F, -16.0F, -16.0F, 26.0F, 6.0F, 32.0F)
                        .texOffs(136, 92).addBox(9.0F, -18.0F, 6.0F, 6.0F, 8.0F, 12.0F)
                        .texOffs(65, 117).addBox(-8.0F, -18.0F, -8.0F, 16.0F, 2.0F, 16.0F),
                PartPose.offset(0.0F, 0.0F, 0.0F));

        PartDefinition turret = hull.addOrReplaceChild("turret",
                CubeListBuilder.create()
                        .texOffs(173, 92).addBox(-8.0F, -4.0F, -8.0F, 16.0F, 4.0F, 16.0F)
                        .texOffs(0, 92).addBox(-10.0F, -8.0F, -10.0F, 20.0F, 4.0F, 20.0F)
                        .texOffs(0, 117).addBox(-8.0F, -12.0F, -8.0F, 16.0F, 4.0F, 16.0F)
                        .texOffs(163, 117).addBox(-7.0F, -14.0F, -6.0F, 14.0F, 2.0F, 13.0F)
                        .texOffs(130, 117).addBox(-16.0F, -11.0F, -11.0F, 6.0F, 8.0F, 10.0F)
                        .texOffs(186, 138).addBox(-15.0F, -10.0F, -12.0F, 4.0F, 4.0F, 1.0F)
                        .texOffs(186, 53).addBox(10.0F, -12.0F, -3.0F, 6.0F, 10.0F, 15.0F),
                PartPose.offset(0.0F, -18.0F, 0.0F));

        PartDefinition barrels = turret.addOrReplaceChild("barrels",
                CubeListBuilder.create()
                        .texOffs(81, 92).addBox(-6.0F, -5.0F, -3.0F, 12.0F, 9.0F, 15.0F)
                        .texOffs(218, 117).addBox(-3.5F, -4.0F, -11.4F, 6.0F, 6.0F, 8.0F)
                        .texOffs(117, 53).addBox(-2.5F, -3.0F, -41.0F, 4.0F, 4.0F, 30.0F)
                        .texOffs(121, 138).addBox(-3.0F, -3.5F, -44.0F, 5.0F, 5.0F, 3.0F),
                PartPose.offset(0.0F, -6.0F, -10.0F));

        PartDefinition radar = turret.addOrReplaceChild("radar",
                CubeListBuilder.create()
                        .texOffs(138, 138).addBox(-3.0F, -2.0F, -1.0F, 6.0F, 4.0F, 4.0F),
                PartPose.offset(0.0F, -13.0F, 8.0F));

        radar.addOrReplaceChild("radar_r0",
                CubeListBuilder.create()
                        .texOffs(0, 138).addBox(-8.0F, -11.0F, 0.0F, 16.0F, 11.0F, 2.0F),
                PartPose.offsetAndRotation(-0.0F, -1.0F, 0.0F, 0.3142F, -0.0000F, 0.0000F));

        radar.addOrReplaceChild("radar_r1",
                CubeListBuilder.create()
                        .texOffs(159, 138).addBox(-6.0F, -9.0F, -1.0F, 12.0F, 7.0F, 1.0F),
                PartPose.offsetAndRotation(-0.0F, -1.0F, 0.0F, 0.3142F, -0.0000F, 0.0000F));

        return LayerDefinition.create(mesh, 256, 256);
    }

    public static LayerDefinition createTerrahawkPaladin() {
        MeshDefinition mesh = new MeshDefinition();
        PartDefinition root = mesh.getRoot();

        PartDefinition hull = root.addOrReplaceChild("hull",
                CubeListBuilder.create()
                        .texOffs(0, 0).addBox(-21.0F, -24.0F, -26.0F, 42.0F, 20.0F, 52.0F)
                        .texOffs(37, 189).addBox(21.0F, -22.0F, -23.0F, 1.0F, 16.0F, 4.0F)
                        .texOffs(48, 189).addBox(-22.0F, -22.0F, -23.0F, 1.0F, 16.0F, 4.0F)
                        .texOffs(169, 189).addBox(21.0F, -22.0F, -17.0F, 1.0F, 16.0F, 3.0F)
                        .texOffs(178, 189).addBox(-22.0F, -22.0F, -17.0F, 1.0F, 16.0F, 3.0F)
                        .texOffs(59, 189).addBox(21.0F, -22.0F, -12.0F, 1.0F, 16.0F, 4.0F)
                        .texOffs(70, 189).addBox(-22.0F, -22.0F, -12.0F, 1.0F, 16.0F, 4.0F)
                        .texOffs(81, 189).addBox(21.0F, -22.0F, -6.0F, 1.0F, 16.0F, 4.0F)
                        .texOffs(92, 189).addBox(-22.0F, -22.0F, -6.0F, 1.0F, 16.0F, 4.0F)
                        .texOffs(103, 189).addBox(21.0F, -22.0F, 0.0F, 1.0F, 16.0F, 4.0F)
                        .texOffs(114, 189).addBox(-22.0F, -22.0F, 0.0F, 1.0F, 16.0F, 4.0F)
                        .texOffs(125, 189).addBox(21.0F, -22.0F, 6.0F, 1.0F, 16.0F, 4.0F)
                        .texOffs(136, 189).addBox(-22.0F, -22.0F, 6.0F, 1.0F, 16.0F, 4.0F)
                        .texOffs(187, 189).addBox(21.0F, -22.0F, 12.0F, 1.0F, 16.0F, 3.0F)
                        .texOffs(196, 189).addBox(-22.0F, -22.0F, 12.0F, 1.0F, 16.0F, 3.0F)
                        .texOffs(147, 189).addBox(21.0F, -22.0F, 17.0F, 1.0F, 16.0F, 4.0F)
                        .texOffs(158, 189).addBox(-22.0F, -22.0F, 17.0F, 1.0F, 16.0F, 4.0F)
                        .texOffs(0, 73).addBox(-18.0F, -29.0F, -23.0F, 36.0F, 5.0F, 46.0F)
                        .texOffs(230, 212).addBox(12.0F, -5.0F, -19.0F, 4.0F, 5.0F, 4.0F)
                        .texOffs(0, 229).addBox(12.0F, -5.0F, 15.0F, 4.0F, 5.0F, 4.0F)
                        .texOffs(17, 229).addBox(-16.0F, -5.0F, -19.0F, 4.0F, 5.0F, 4.0F)
                        .texOffs(34, 229).addBox(-16.0F, -5.0F, 15.0F, 4.0F, 5.0F, 4.0F)
                        .texOffs(11, 212).addBox(-7.0F, -20.0F, 25.0F, 14.0F, 14.0F, 1.0F),
                PartPose.offset(0.0F, 0.0F, 0.0F));

        PartDefinition turret = hull.addOrReplaceChild("turret",
                CubeListBuilder.create()
                        .texOffs(109, 125).addBox(-11.0F, -5.0F, -12.0F, 22.0F, 5.0F, 24.0F)
                        .texOffs(0, 125).addBox(-13.0F, -10.0F, -14.0F, 26.0F, 5.0F, 28.0F)
                        .texOffs(0, 159).addBox(-11.0F, -15.0F, -12.0F, 22.0F, 5.0F, 24.0F)
                        .texOffs(67, 212).addBox(-11.0F, -5.0F, -16.0F, 22.0F, 5.0F, 9.0F)
                        .texOffs(130, 212).addBox(-11.0F, -9.0F, -14.0F, 22.0F, 4.0F, 7.0F)
                        .texOffs(51, 229).addBox(-11.0F, -14.0F, -11.0F, 22.0F, 5.0F, 4.0F)
                        .texOffs(158, 159).addBox(-10.0F, -17.0F, -10.0F, 20.0F, 2.0F, 20.0F)
                        .texOffs(0, 189).addBox(-19.0F, -13.0F, -16.0F, 6.0F, 10.0F, 12.0F)
                        .texOffs(138, 229).addBox(-18.0F, -11.0F, -17.0F, 4.0F, 5.0F, 1.0F),
                PartPose.offset(0.0F, -29.0F, 0.0F));

        PartDefinition barrels = turret.addOrReplaceChild("barrels",
                CubeListBuilder.create()
                        .texOffs(93, 159).addBox(-7.0F, -6.0F, -4.0F, 14.0F, 10.0F, 18.0F)
                        .texOffs(205, 189).addBox(-3.0F, -4.0F, -13.7F, 6.0F, 6.0F, 10.0F)
                        .texOffs(165, 73).addBox(-2.0F, -3.0F, -48.0F, 4.0F, 4.0F, 34.0F)
                        .texOffs(104, 229).addBox(-2.5F, -3.5F, -51.0F, 5.0F, 5.0F, 3.0F),
                PartPose.offset(0.0F, -7.0F, -14.0F));

        PartDefinition radar = turret.addOrReplaceChild("radar",
                CubeListBuilder.create()
                        .texOffs(42, 212).addBox(-3.0F, -9.0F, -3.0F, 6.0F, 9.0F, 6.0F),
                PartPose.offset(0.0F, -17.0F, 0.0F));

        radar.addOrReplaceChild("radar_r0",
                CubeListBuilder.create()
                        .texOffs(238, 189).addBox(9.0F, -13.0F, 0.0F, 2.0F, 13.0F, 3.0F),
                PartPose.offsetAndRotation(-0.0F, -8.0F, 0.0F, 0.2094F, -0.0000F, 0.0000F));

        radar.addOrReplaceChild("radar_r1",
                CubeListBuilder.create()
                        .texOffs(0, 212).addBox(-11.0F, -13.0F, 0.0F, 2.0F, 13.0F, 3.0F),
                PartPose.offsetAndRotation(-0.0F, -8.0F, 0.0F, 0.2094F, -0.0000F, 0.0000F));

        radar.addOrReplaceChild("radar_r2",
                CubeListBuilder.create()
                        .texOffs(149, 229).addBox(-11.0F, -2.0F, 0.0F, 22.0F, 2.0F, 3.0F),
                PartPose.offsetAndRotation(-0.0F, -8.0F, 0.0F, 0.2094F, -0.0000F, 0.0000F));

        radar.addOrReplaceChild("radar_r3",
                CubeListBuilder.create()
                        .texOffs(200, 229).addBox(-11.0F, -13.0F, 0.0F, 22.0F, 2.0F, 3.0F),
                PartPose.offsetAndRotation(-0.0F, -8.0F, 0.0F, 0.2094F, -0.0000F, 0.0000F));

        radar.addOrReplaceChild("radar_r4",
                CubeListBuilder.create()
                        .texOffs(189, 212).addBox(-9.0F, -11.0F, 1.0F, 18.0F, 9.0F, 2.0F),
                PartPose.offsetAndRotation(-0.0F, -8.0F, 0.0F, 0.2094F, -0.0000F, 0.0000F));

        radar.addOrReplaceChild("radar_r5",
                CubeListBuilder.create()
                        .texOffs(121, 229).addBox(-1.0F, -7.0F, -5.0F, 2.0F, 2.0F, 6.0F),
                PartPose.offsetAndRotation(-0.0F, -8.0F, 0.0F, 0.2094F, -0.0000F, 0.0000F));

        return LayerDefinition.create(mesh, 256, 256);
    }

    public static LayerDefinition createMantis() {
        MeshDefinition mesh = new MeshDefinition();
        PartDefinition root = mesh.getRoot();

        PartDefinition hull = root.addOrReplaceChild("hull",
                CubeListBuilder.create()
                        .texOffs(0, 0).addBox(-20.0F, -10.0F, -20.0F, 40.0F, 7.0F, 40.0F)
                        .texOffs(188, 161).addBox(16.0F, -9.0F, -15.0F, 6.0F, 4.0F, 4.0F)
                        .texOffs(193, 142).addBox(15.0F, -5.0F, -16.0F, 6.0F, 5.0F, 6.0F)
                        .texOffs(209, 161).addBox(16.0F, -9.0F, 11.0F, 6.0F, 4.0F, 4.0F)
                        .texOffs(218, 142).addBox(15.0F, -5.0F, 10.0F, 6.0F, 5.0F, 6.0F)
                        .texOffs(230, 161).addBox(-24.0F, -9.0F, -15.0F, 6.0F, 4.0F, 4.0F)
                        .texOffs(0, 161).addBox(-21.0F, -5.0F, -16.0F, 6.0F, 5.0F, 6.0F)
                        .texOffs(0, 173).addBox(-24.0F, -9.0F, 11.0F, 6.0F, 4.0F, 4.0F)
                        .texOffs(25, 161).addBox(-21.0F, -5.0F, 10.0F, 6.0F, 5.0F, 6.0F)
                        .texOffs(0, 48).addBox(-12.0F, -20.0F, -14.0F, 24.0F, 10.0F, 28.0F)
                        .texOffs(0, 87).addBox(12.0F, -22.0F, 2.0F, 7.0F, 12.0F, 16.0F)
                        .texOffs(47, 87).addBox(-19.0F, -22.0F, 2.0F, 7.0F, 12.0F, 16.0F)
                        .texOffs(144, 161).addBox(-3.0F, -23.0F, 10.0F, 6.0F, 3.0F, 6.0F)
                        .texOffs(71, 173).addBox(-1.5F, -26.0F, 11.5F, 3.0F, 3.0F, 3.0F),
                PartPose.offset(0.0F, 0.0F, 0.0F));

        PartDefinition turret = hull.addOrReplaceChild("turret",
                CubeListBuilder.create()
                        .texOffs(0, 116).addBox(-9.0F, -5.0F, -10.0F, 18.0F, 5.0F, 20.0F)
                        .texOffs(94, 87).addBox(-11.0F, -9.0F, -12.0F, 22.0F, 4.0F, 24.0F)
                        .texOffs(77, 116).addBox(-9.0F, -14.0F, -10.0F, 18.0F, 5.0F, 20.0F)
                        .texOffs(103, 142).addBox(-9.0F, -4.0F, -14.0F, 18.0F, 4.0F, 8.0F)
                        .texOffs(50, 161).addBox(-9.0F, -9.0F, -12.0F, 18.0F, 5.0F, 6.0F)
                        .texOffs(21, 173).addBox(-9.0F, -13.0F, -10.0F, 18.0F, 4.0F, 4.0F)
                        .texOffs(189, 116).addBox(-8.0F, -16.0F, -8.0F, 16.0F, 2.0F, 16.0F)
                        .texOffs(154, 116).addBox(-17.0F, -12.0F, -14.0F, 6.0F, 9.0F, 11.0F)
                        .texOffs(84, 173).addBox(-16.0F, -10.0F, -15.0F, 4.0F, 4.0F, 1.0F)
                        .texOffs(106, 173).addBox(-15.0F, -13.0F, -15.0F, 3.0F, 2.0F, 1.0F)
                        .texOffs(105, 48).addBox(11.0F, -13.0F, -4.0F, 6.0F, 11.0F, 18.0F)
                        .texOffs(99, 161).addBox(-10.0F, -8.0F, 12.0F, 20.0F, 8.0F, 2.0F),
                PartPose.offset(0.0F, -20.0F, 0.0F));

        PartDefinition barrels = turret.addOrReplaceChild("barrels",
                CubeListBuilder.create()
                        .texOffs(154, 48).addBox(-7.0F, -7.0F, -4.0F, 14.0F, 11.0F, 18.0F)
                        .texOffs(0, 142).addBox(-4.0F, -5.0F, -15.4F, 7.0F, 7.0F, 11.0F)
                        .texOffs(161, 0).addBox(-3.0F, -4.0F, -56.0F, 5.0F, 5.0F, 41.0F)
                        .texOffs(169, 161).addBox(-3.5F, -4.5F, -59.0F, 6.0F, 6.0F, 3.0F)
                        .texOffs(37, 142).addBox(-4.0F, -5.0F, -16.0F, 8.0F, 8.0F, 8.0F),
                PartPose.offset(0.0F, -7.0F, -12.0F));

        PartDefinition radar = turret.addOrReplaceChild("radar",
                CubeListBuilder.create()
                        .texOffs(70, 142).addBox(-4.0F, -5.0F, -4.0F, 8.0F, 5.0F, 8.0F)
                        .texOffs(156, 142).addBox(-6.0F, -11.0F, -3.0F, 12.0F, 6.0F, 6.0F)
                        .texOffs(95, 173).addBox(1.0F, -10.0F, -4.0F, 4.0F, 3.0F, 1.0F)
                        .texOffs(66, 173).addBox(-0.5F, -18.0F, 0.0F, 1.0F, 7.0F, 1.0F),
                PartPose.offset(0.0F, -16.0F, 0.0F));

        return LayerDefinition.create(mesh, 256, 256);
    }
    /** Model for one turret type. */
    public static LayerDefinition create(TurretKind kind) {
        return switch (kind) {
            case GEPARD -> createGepard();
            case SLINGER -> createSlinger();
            case TERRAHAWK_PALADIN -> createTerrahawkPaladin();
            case MANTIS -> createMantis();
        };
    }

    private TurretLayers() {
    }
}
